language: cpp
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls

script: cmake -Dtest=1 && make && ./bin/runUnitTests 
#&& coveralls --exclude lib --exclude tests --gcov-options '\-lp'


