language: cpp
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls

script: cd makefile && make test && ../bin/unittest
after_success:
  - cd obj && coveralls --exclude lib --exclude tests --gcov-options '\-lp'

